### ISSUE TITLE
无法启用这个插件：AttributeError: module 'bpy.utils' has no attribute 'register_module'

### ISSUE THREAD

**Issue by lvyanxi** [nathanfaucett/Blender-JSON-Exporter#1]
Traceback (most recent call last):
  File "C:\Users\qwer1\Downloads\blender-4.1.0-windows-x64\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\qwer1\Downloads\blender-4.1.0-windows-x64\4.1\scripts\addons\io_mesh_json\__init__.py", line 75, in register
    bpy.utils.register_module(__name__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bpy.utils' has no attribute 'register_module'

Traceback (most recent call last):
  File "C:\Users\qwer1\Downloads\blender-4.1.0-windows-x64\4.1\scripts\modules\addon_utils.py", line 444, in enable
    mod.register()
  File "C:\Users\qwer1\Downloads\blender-4.1.0-windows-x64\4.1\scripts\addons\io_mesh_json\__init__.py", line 75, in register
    bpy.utils.register_module(__name__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'bpy.utils' has no attribute 'register_module'

**Comment by nathanfaucett** [comment]
sorry, I wrote this like 10 years ago and it is not maintained anymore, please fork and fix it if you want but I do not work on this anymore.
